spring:
  application:
    name: simple-discovery-server 

server:
  port: ${port:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
