spring:
  application:
    name: simple-discovery-server 
    
info:
  description: 'simple-discovery-server, called Eureka. (port: ${server.port})'

server:
  port: ${port:8761}

# development only (non-secured)
management:
  security:
    enabled: false

eureka:
  server:
    enable-self-preservation: true
  instance:
    appname: simple-discovery-server-testapp
    hostname: ${vcap.application.uris[0]:localhost}
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    # it must set variable server port when it registers itself
    serviceUrl:
      defaultZone: http://localhost:${server.port:8761}/eureka/
    enabled: ${example.eureka.client.enabled:true}
