spring:
  application:
    name: simple-discovery-server 
    
info:
  description: 'simple-discovery-server, called Eureka. (port: ${server.port})'

server:
  port: ${port:8761}

eureka:
  server:
    enable-self-preservation: true
  instance:
    appname: simple-discovery-server-testapp
    hostname: ${vcap.application.uris[0]:localhost}
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    #serviceUrl:
    #  defaultZone: http://localhost:${server.port}/eureka
      
      
    